- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
- Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
닉네임 생성 UI 구현입니다. 
- 닉네임 뷰 라벨 생성
- 텍스트필드 생성
- 텍스트필드 제한 구현
- 키보드 위치에 따라 애니메이션 
- 메인버튼 생성
- 메인버튼 활성화 비활성화
- 텍스트 필드 컴포넌트화 하기
- 11번 브랜치로 이동해 오셔서 보고 가셔요~~!!
https://user-images.githubusercontent.com/59243274/196462305-afceacd6-6c0c-4ebb-b0c7-ebe54b02057c.mp4
한 화면에 대한 pr을 한번에 날리게 됐는데 이것도 하나하나 나눠서 하는게 좋을지 궁금합니다. 
사실 제가 맡은 화면은 내용이 많지 않아서 하나로 해도 되겠다고 판단했지만 막상 UI구현하고 나니 아무래도 없던 파일이 생성되는것이다보니 리뷰가 많네요.
다음 pr 부터는 컴포넌트 하나하나에 pr로 해볼까? 라는 생각인데 어떻게 생각하시는지 의견 주시면 감사하겠습니다
- close #11
> [FEAT] 닉네임 생성 UI 구현

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/KeywordLabel.swift
- Maddori.Apple/Maddori.Apple/Screen/View/HomeViewController.swift
자주 쓰이게 될 키워드를 UIComponent로 빼뒀습니다!
처음에 UIView 위에 UILabel을 씌우는걸 생각해봤는데, @dangsal 호야가 좋은 방법을 알려줘서 그대로 했습니다
UILabel 을 그릴 때 주변에 패딩을 주어 사이즈도 알아서 맞춰주는..!
참고 사이트는 하단에 넣어뒀습니다~
저희가 키워드가 총 4종류가 있는데요
(네이밍은 피그마에 지정해둔걸로 따랐습니다(preview는 그냥 제가 알아서 함..))
- defaultKeyword
- subKeyword
- disabledKeyword
- previewKeyword
키워드 레이블 넣을 때 keywordType을 위 4가지 중 하나로 지정해주면 디자인에 맞게 변경됩니당
현재 HomeViewController를 만들어서 내부에서 테스트 중이었습니당
해당 파일 안에 firstLabel과 secondLabel 프로퍼티를 조절해보면 됩니당
예를 들어서
```swift
private let firstLabel: KeywordLabel = {
let keyword = KeywordLabel()
keyword.keywordType = .disabledKeyword // -> .defaultKeyword 로 바꿔보시면 됩니다
keyword.text = "첫 djdkdkdk번째"
return keyword
}()
```
원래 디자인은 defaultKeyword는 gradient가 들어가야 하는데, 
이걸 넣게 되면 UILabel 위에 gradient layer를 덧씌우게 됩니다
여기서 문제가 발생하는데, UILabel 위에 덧씌우게 되면 텍스트가 보이지 …
> [ADD] KeywordLabel 컴포넌트화 완료

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
- 팀 생성하기 버튼으로 나오는 화면입니다.
- 이전 pr 에서 연결되는 pr이라 이전께 머지되면 파일 체인지가 줄어들겁니다
- 여기서 추가한 부분은 CreateTeam 이라는 뷰컨이고 이 안에는 타이틀, 플레이스홀더, 버튼 타이틀이 변경되었고
- 텍스트필드의 제한 숫자도 받아줘야겠다 생각이 들어 이것도 받는것으로 변경했습니다.
- CreateTeamViewController 생성
- 타이틀, 플레이스홀터, 버튼 타이틀 오버라이드
- 제한 숫자 받는걸로 변경
- 10으로 오버라이드
feature/22-createTeam 으로 오셔서 신델리게이트는 CreateTeamViewController 로 변경하시면 됩니다.
- 팀합류 PR 이 머지 된 후 보시는걸 추천드립니다. 
- 여기서는 네비게이션의 x버튼을 하지 않았습니다. 
- 해도 되지만 이부분은 연결할때 뷰들을 확인하면서 한번에 하는게 속도 상 빠를것이라고 판단했습니다.
- close #25
> [FEAT] 팀생성 UI 구현

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/Date+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/FeedbackTextView.swift
- Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
키워드 추가하기 페이지에서 Start 부분을 추가해서 구현했습니다
- Start 라벨과 토글 추가
- Start 토글 터치시 Start 내용 TextView 등장
- TextView & TextField 눌렀을 때 ScrollView 위치 이동 -> 작성하기 편하도록
- DoneButtonView 추가 -> 뒤에 흰색 background 추가하기 위해
- ButtonTopLabel 추가 -> 회고 날짜 유무에 따라 분기 처리
- Date Extension 추가
feature/19-add-feedback-start 로 오셔서 root를 AddFeedbackContentViewController 로 바꾼 후핸드폰에 빌드해보시면 감사하겠습니다!
https://user-images.githubusercontent.com/81340603/197524849-2fbd57a6-8a76-4405-82bb-34b7ea62982e.MP4
- TextView나 TextField가 가려지지 않도록 해당 부분을 터치했을 때 ScrollView를 이동시키도록 했는데 그 값을 상수로 줬습니다.. 기기마다 다르게 보일 것 같은데 더 좋은 방법 아시는 분 말씀 부탁드려요..
- ScrollView에 올라갈 ContentView의 height 를 지정해줘야 하는데 Start의 유무에 따라 길이가 자동 조정되도록 하는 방법을 이 글을 적으면서 깨달았어요.. Toggle 누를 때 height 값을 바꾸면 되는 군요..! 수정해보겠습니다!
- close #19 …
> [FEAT] Start 피드백 추가하기 구현

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Network/Feedback/Feedback.swift
- Maddori.Apple/Maddori.Apple/Network/ReflectionInfo/ReflectionInfoModel.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackHeaderView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/66 이 PR에 이어서 아랫부분 작업 했습니다 !
| 전체 View | 작업 한 부분 |
|---|---|
|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199454861-43c6a19f-f5e9-4a84-a4c2-6800ee12fc44.png">|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199510966-e22b8d9c-5958-4852-a7fc-f01d7e100e49.png">|
앞선 PR에선 멤버들의 CollectionView를 만들었는데, 이어서 네모 체크해놓은 피드백 받은 부분의 CollectionView를 만들었습니다 !
feature/65-feedback-collectionview 브랜치로 오셔서 SceneDelegate를 MyBoxViewController로 변경해주세요 !
Network/Feedback 폴더에 Feedback이라는 `struct`를 만들어 뒀는데, 거기에 목데이터를 추가하시면서 데이터가 잘 추가되는지 확인해주시면 됩니다 !
https://user-images.githubusercontent.com/78677571/199657363-7a72bb4d-c678-4d04-8142-6ea8677ec58c.mp4
앞선 PR과 이번 PR에선 …
> [ADD] 보관함 Feedback CollectionView 생성

- Maddori.Apple/Maddori.Apple/Network/Feedback/Feedback.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackHeaderView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
보관함 탭 부분의 앞선 두 PR에 이어서 마지막 divider(구분선)을 추가하는 PR입니다.
| 전체 View | 작업 한 부분 |
|---|---|
|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199454861-43c6a19f-f5e9-4a84-a4c2-6800ee12fc44.png">|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199670475-58b5c568-894e-454c-8535-1a2bdc91ebdd.png">|
feature/65-feedback-collectionview 브랜치로 오셔서 SceneDelegate를 MyBoxViewController로 변경해주세요 !
CollectionView의 스크롤을 막했을때 재사용되서 divider의 문제가 없는지 확인부탁드립니다 (제가 했을 땐 없었습니다)
https://user-images.githubusercontent.com/78677571/199670959-41f99208-1b48-4574-8568-bce14cef638e.mp4
Divider를 직접 만들어서 넣고 있었는데, @seongmin221 가 collectionview를 list로 만들어주는게 있다 그래서 적용해보려 했는데, 내부 셀들을 구분해주지만 섹션까지 깔끔하게 구분해주는지는 잘 모르겠더라구요. 우선은 이렇게도 만들 수 있어서 직접 구분선을 만들어두었습니다. 
추후에 …
> [ADD] FeedBack CollectionView Divider 추가

- Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
보관함뷰를 만들때 mockData로 구현을 해뒀는데, Continue와 Stop이 둘 다 있다는 생각으로 만들었습니다. 근데 Stop만 있을 때는 해당 View가 뜨지 않는 문제가 있었습니다. 해당 문제를 해결했습니다.
버그를 제보해주셔서 감사합니다 @seongmin221 
피드백이 Stop만 있더라도 Stop만 표시되게끔 (정상적으로) 구현했습니다.
feature/79-mybox-stop-issue 브랜치로 오셔서 SceneDelegate를 MyBoxViewController 로 수정해주세요
Network/Feedback/Feedback.swift 의 mockData들 중에서 continue부분을 다 주석처리하고 실행시켜보면 됩니다 !
https://user-images.githubusercontent.com/78677571/200169015-f9695cbc-6163-4eb3-a38e-6d6a5b255303.mp4
delegate collectionView 모든 함수에서 continue가 있는지 체크하고 조건문을 걸었는데, 더 나은 방식이 있을 것 같다는 생각이 들었습니다. 현재는 급해서 전부다 if를 넣어서 처리해뒀습니다.
- close #79
> [CHORE] Stop만 있을 때 안뜨는 문제 해결

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Model/BaseModel.swift
- Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
- Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
setup 부분의 view들의 API 연결을 했습니다. 우리 모두 Alamofire를 처음 써보는거라 api 몇개만 뚫으면 금방 할 수 있다는 생각에 3개정도 뚫었습니다. 아자아자 화이팅 !
- 닉네임 설정뷰 (SetNicknameViewController)
- 팀 생성뷰 (CreateTeamViewController)
- 팀 합류뷰 (JoinTeamViewController)
에 연결되는 API들을 추가했습니다 .
feature/105-setup-view-api 브랜치로 오셔서 sceneDelegate에 있는 `isLogined = false`로 변경하고 
닉네임 설정, 팀 생성, 팀 합류하기를 테스트 해보시면 됩니다 !
팀 합류 코드는 **EJHLFR** 로 사용하시면 됩니다.
https://user-images.githubusercontent.com/78677571/202142639-2cc7b6b8-aabf-4594-a000-2d9c17c223d0.mp4
https://user-images.githubusercontent.com/78677571/202142670-11a156de-26c3-442f-9df1-9f81263d3b03.mp4
ViewController에서 각 API마다 함수를 만들어서 사용하려고 했습니다. 그렇게 했을때 사소한 실수가 생길 수 있을 것 같아서 해당 view들이 정리된 EndPoint를 만들었습니다.
다른분들도 EndPoint형식으로 만들고 사용하면 좋을 것 같습니다 !
추가적으로 EndPointable 이라는 프로토콜을 만들어서 확실히 하고 싶은데 추후에 추가 해보겠습니다 ! …
> [FEAT] Setup View들 API연결 완료

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Network/Response/AddReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/AllCertainTypeFeedBackResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/AllFeedBackResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/AllReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/CreateTeamResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/CurrentMemberResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/CurrentReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/EditFeedBackResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/FeedBackContentResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/FeedBackInfoResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/FeedBackResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/KeywordResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/ReflectionInfoResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/ReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Network/Response/TeamInfoResponse.swift
몇몇 API의 response값의 변수명이 수정되었습니다. 
API에서 response값이 변경되면서 그에 따른 변수명들을 수정했습니다.
어떤 Response가 어떤 API인지 보기 헷갈려서 mark 주석으로 추가해뒀습니다 !
노션에도 클라 모델명으로 추가해뒀습니다 !
주석을 이렇게 사용하는게 나쁜 방법일 수 도 있지만, 개발자들의 시간을 단축시키는데 조금이라도 도움이 된다면 저는 써도 좋다 생각해서 해당 주석들을 추가했습니다 !
추가적으로 변수명이 노션과 조금 다른부분은 서버분들께 연락드린 상태입니다 !
- close #111
> [CHORE] API 수정에 따른 모델 수정

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/AddFeedBackEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/FeedBackContentDTO.swift
- Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
특정 팀원에게 피드백을 추가하는 API를 연결했습니다. 
피드백 추가하기 API 연결
현재 멤버를 선택하는 컬렉션 뷰가 공통으로 사용되고 있었는데, 피드백을 추가할 땐 해당 cell이 선택되었다고 표시될 필요가 없습니다. 그 부분까지 같이 수정했습니다.
현재 팀의 멤버들을 불러오는 과정에서 id값도 같이 오는데, 그 값을 다음 뷰컨으로 넘겨주는 방식으로 사용했습니다 !
feature/113-add-feedback-api 브랜치로 오셔서, 실제 피드백을 추가해보시면 됩니다 !
https://user-images.githubusercontent.com/78677571/202396531-c0f2b172-9a89-44d7-89e0-807dff99cfca.mp4
현재 teamId, reflectionId, userId들은 하드코딩방식으로 넣어뒀습니다.
추후에 수정하려고 fixme를 적어두었습니다 !
- close #113
> [FEAT] 피드백 추가하기 API 연결

- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/AddFeedBackEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
테스트 하는 과정에서, 다같이 한 팀에 들어와서 서로에게 피드백을 보내고 그 데이터로 다른 API들을 테스트하기 위함입니다.
HomeViewController에서 데이터가 로드 안되는 문제를 해결했습니다. 안되던 이유는 guard let으로 nil값을 풀다가 guard let 구문에 걸려서 실행이 안되는 문제였습니다.
현재 팀의 멤버에게 피드백을 작성할 수 있게 구현했습니다 
`MemberResponse` 모델의 id값이 userId로 변경되어 있어서 그 부분을 수정했습니다 !
테스트할 땐 teamId가 3 이어야합니다. 혹시 다른 작업하다가 UserDefault의 teamId가 바뀌었다면 3번으로 수정 될 수 있게 처리한 후 테스트해주세요 ! 
userId도 현재 팀에 들어와있는 id값 이어야 합니다. 아까 현재 회고에 들어오신 id 값을 사용하시면 됩니다 !
https://user-images.githubusercontent.com/78677571/202709230-d43e354a-95c4-47aa-928a-86ca00b64a8b.MP4
현재 HomeViewController에서 현재 회고에 대한 정보를 불러올 때
이 4개의 데이터중 `current_reflection_id`, `reflection_name` 이 두 데이터만 무조건 있고, 나머지 두개 데이터는 값이 비어있거나 없을수가 있어서 `guard let`구문으로 풀면 오류가 생길 수 있습니다. 
현재는 fixme를 적어두고 아래에서 if let으로 처리해두었습니다.
- close #133
> [FEAT] 현재 팀, 현재 회고의 피드백 추가하기 기능 추가

- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
백로그의 <뒤에 버튼 뷰넣기! 버튼용 백그라운드 뷰!>를 하는 김에
<회고 일정 생성과 관련된 리더/멤버 분기 처리 구현하기>도 같이 구현해뒀습니다!
- 회고 일정 만들기 뒤에 백그라운드 뷰 생성
- 회고 일정 생성 관련 리더 / 멤버 분기처리
총 3가지 상태가 있는데, 헷갈리지 않게 DB와 UserDefaults의 userId를 잘 바꿔가면서 테스트 해봐야 합니다!
1. teamId = 3, userId = 6 (맛도리테스트 팀에 admin일 때), DB에 회고 일정 SettingRequired일 때
2. teamId = 6, userId = 11 (홀리몰리 팀에 admin일 때), DB에 회고 일정 Before일 때 (다른거 테스트 하고 있는 관계로 홀리몰리팀으로 진행했습니다!)
3. teamId = 3, userId = 9 (맛도리테스트 팀에 admin 아닐 때)
1, 2 상황은 SceneDelegate에 
`UserData.setValue(6, forKey: .userId)`
`UserData.setValue(3, forKey: .teamId)`
를 넣고 실행하면 되구요,
**(2 상황은 값 다릅니다! 위에 2 상황 확인하고 넣어주세요!!)**
3번 상황은  SceneDelegate에 
`UserData.setValue(9, forKey: .userId)`
`UserData.setValue(3, forKey: .teamId)`
를 넣고 실행하면 됩니다!
DB는... 저한테 요청을 해주세요!! 밥먹을 때 아니면 슬랙 잘 보고 있을겁니다 하핳
|<img …
> [CHORE] HomeView isAdmin 인지에 따라 분기처리 완료

- Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
보관함 탭 부분에 테스트할 DB가 없어서 테스트를 못하고 있었는데, 앞선 PR들로 테스트 할 수 있게 연결되어서 테스트 후 정상 작동하는 걸 확인하고 PR날립니다
항상 감사합니다 선생님들..❤️
보관함 탭에서 현재 팀원들의 멤버 목록 불러오는 API랑 View 랑 연결시켜뒀습니다 !
해당 멤버의 cell을 누르면 내가 해당 멤버에게 보낸 피드백을 볼 수 있습니다 !
feature/136-myfeedback-view-api 브랜치로 오셔서 실행시키면 됩니다 !
현재 회고중 상태라서 테스트가 가능한데, 상태가 변경되면 어떻게 될 지 모르겠습니다 !
피드백 추가해서 반영되는지 확인하려 했지만, 현재 회고가 진행중이라 피드백 추가가 안되더라구요 ... ㅠ 아마 잘 될겁니다 !
https://user-images.githubusercontent.com/78677571/202775167-de494ccd-cdef-40b4-bd65-adb2809728f0.mov
현재 탭으로 바로 들어왔을 때 첫번째 셀 (케미) 부분이 자동으로 load되지 않는데 어떤 방법을 쓰면 좋을지 생각중입니다..
피드백을 보여주는 collectionView 부분을 급하게 수정하느라 중복되는 코드들이 좀 있는데, 이 PR이 머지되기 전에 수정하겠습니다.
- close #136
> [FEAT] 보관함 탭 API + View 연결

- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
백로그의 <초대코드 복사 로직 추가하기>의 HomeView 파트입니다!
HomeView의 상단 초대코드 버튼을 터치하면 코드가 복사되고, 햅틱도 추가해뒀습니다!
그냥 아무 팀에 들어가서 실행해보세요!!
https://user-images.githubusercontent.com/72431640/202890877-ea3dc062-c83f-4e6f-95f7-ac1ffb3f716a.MP4
showToastPopup이 현재는 warning만 지원했는데, type을 지정해서 warning 일 때, complete 일 때 선택할 수 있도록 바꿔뒀습니다!
- close #143
> [CHORE] HomeView invitationCode 복사 구현

- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
백로그의 <나의 회고 디테일에서 이름 뷰 잘림>을 해결하기 위해 나온 PR 입니다!
- constraints 조정
```swift
UserDefaultHandler.clearAllData()
UserData.setValue(11, forKey: .userId)
UserData.setValue(6, forKey: .teamId)
UserData.setValue(true, forKey: .isLogin)
```
를 SceneDelegate에 넣어서 '나의 회고' 아무 회고 들어가서 확인하시면 됩니다!
- close #163
> [CHORE] MyReflectionDetail의 Cell에 이름 lable 사이즈 재조정

- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
어제 급하게 merge하다가 미처 확인 못한 버그를 발견하고 급하게 수정했습니다 !
viewWillAppear에서 멤버 리스트를 불러오는 함수를 실행시키는데, 그 함수내에선 memberList에 append 하는 형식으로 추가를 했었습니다.
다른탭을 갔다온다해서 viewController가 새로 그려지는게 아니라 이미 존재하는 배열의 데이터가 사라지지 않습니다. 근데 viewWillAppear에서 계속 append해서 무한정 길어지는 문제가 생겼습니다 !
다른탭 눌렀다가 보관함 탭 눌렀다가 하시면 됩니다 !
https://user-images.githubusercontent.com/78677571/203674478-c7e6fdc3-af31-4323-a3d7-a0294fa53d9d.mp4
https://user-images.githubusercontent.com/78677571/203674455-427f35ab-79e7-411d-b023-8194bda36a35.mp4
어제 너무 급하게 수정하고 급하게 Approve받았는데, 그 과정에서 놓친 문제네요...
조금은 여유를 갖고 했어야 했네요.. 죄송합니다 .. 하하
- close #167
> [FIX] 보관함 탭 멤버 리스트 쌓이는 문제 해결

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/LogOutButton.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
너무나 놀랐습니다.. 저희가 로그아웃이 없더군요.... 흐흐.. 그래서 일단 로그아웃을 구현했습니다. 
(디자인 적으로 설정뷰가 앞으로 필요할것이라고 생각합니다. 디자인이 새로 나온다면 바꾸는 것으로 생각하겠습니다!)
- 로그아웃 버튼 생성
- 로그아웃 기능 구현
- 나의 회고 탭에 넵비게이션 우측 아이콘에 로그아웃 아이콘을 넣어 놨습니다. 로그아웃을 해보십쇼 후후
- close #165
> [FEAT] 로그아웃 구현 

- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
원래 api 상에서 Start 에 nil을 전달하면 에러가 떴지만 nil도 허용하도록 수정되어 시작된 issue입니다.
코드를 작성하다보니 Start 토글이 켜저 있지만 아무 값도 입력하지 않으면 placeholder text가 start 값으로 전달되는 문제가 발생하여 이 부분도 반영하여 수정했습니다!
Start TextView의 Text 가 place holder 와 동일하거나 Start 토글이 꺼져 있을 경우
AddFeedback 에서는 Start content 를 nil로
MyFeedbackEdit에서는 Start Content를 ""로 전달하는 로직 추가
feature/179-fix-start-content-result로 오셔서 
1.새로운 피드백을 Start 없이 작성해보고
2. 그 피드백에 Start 를 추가해보고
3. 다시 Start 토글을 꺼서 Start를 삭제해보세용!
https://user-images.githubusercontent.com/81340603/203935694-d21bad84-9b8c-45bf-9537-64eccf2175a7.mp4
- close #179
> [FIX] Start Content Post 로직 수정하기

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailViewLastCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
마지막 셀일때는 세그먼트 컨트롤이 위치가 겹치는 현상이 있었습니다.
그래서 뱅크셀러드를 참고해보니 마지막 부분은 빈 셀이 있는거 처럼 구현이 되어 있어서 그렇게 수정 완료 했습니다.
- 빈 셀 (MyReflectionDetailViewLastCell) 생성
- 마지막 셀 생성 
- 저번에 재사용문제는 아예 셀 자체를 재사용하지 않고 새로 등록해서 사용하는 것으로 처리 하였습니다.
feature/184-segement-control-position-fix 로 오셔서 실행 후 나의 회고 디테일 부분(세그먼트 컨트롤 있는부분)으로 오셔서 스크롤을 내려서 마지막에 셀과 세그먼트 컨트롤이 겹치는지 확인해주시면 됩니다.
https://user-images.githubusercontent.com/59243274/204229589-cd0af8d3-bcd3-4a33-ae93-a35c41635637.mp4
- 현재 세그먼트 컨트롤이 눌릴때마다 api 통신을 하고 있는데 이건 굉장히 안좋은 낭비라고 생각합니다. 이부분을 고치고 싶었는데 
이 이슈랑 조금은 결이 다르다고 생각해서
- close #184
> [FIX] 나의 회고 디테일에 세그먼트가 겹치는 문제 해결

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/LogOutButton.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/SettingButton.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
앱 심사 리젝 사유로 회원 탈퇴 문제가 나왔습니다. 그로 인해 해당 기능을 추가했습니다.
회원 탈퇴 기능을 추가했습니다.
나의 회고 탭에서 오른쪽위 네비게이션 아이템에 들어있는 ellipsis 버튼을 눌러서 회원 탈퇴를 진행하시면 됩니다.
실제 DB에서 회원탈퇴가 진행됩니다 !
https://user-images.githubusercontent.com/78677571/204236492-c9f0263c-58d3-425c-8733-1a421e70a1a3.mp4
현재는 설정페이지가 따로 없기 때문에 UIMenu로 구현을 했습니다.
추후에 수정된다면 좋을 것 같습니다 !
UXWriting을 제 생각대로 했기 때문에, 수정해야할 것 같다면 말해주십셔 !
- close #183
> [FEAT] 회원탈퇴 기능 추가

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Network/Model/FeedbackFromMe/FeedbackFromMeModel.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
회고가 시작되었음에도 불구하고, 피드백이 수정 삭제가 가능했던 문제가 있었습니다.
- 현재 회고 상태가 진행중이라면 삭제 버튼이 표시되게 끔 만들었고, 진행중이라면 삭제 버튼이 사라지게 만들었습니다.
- guard let 으로 옵셔널값을 확인했던 코드를 사용하고 있지 않았어서, 그 부분을 사용했습니다.
직접 DB를 수정하면서 테스트해보는게 직빵이긴 합니다. 
회고가 시작전일때와 진행중일때 피드백 상세정보를 확인해보시면 됩니다.
그게 아니라면 
```swift
//  FeedbackFromMeDetailViewController.swift
private func setupIsProgressingStatus() {
if feedbackDetail.reflectionStatus != .Before {
navigationItem.setRightBarButton(nil, animated: false)
editFeedbackUntilLabel.setTextWithLineHeight(text: TextLiteral.myFeedbackDetailViewControllerBeforeReflectionLabelNotBefore, lineHeight: 22)
feedbackEditButton.isDisabled = true
}
}
```
요기 271번째 줄에서 != .Before 되어있는 걸 변경해보시면 상태에 따라 바뀐다는걸 확인할 순 있습니다. 
DB바꾸는게 직빵이긴해요... ㅎ
https://user-images.githubusercontent.com/78677571/204434154-3f3ca953-759a-4610-a7 …
> [CHORE] 회고가 진행중으로 넘어갔을 때, 피드백 수정 삭제 불가능하도록 분기처리

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
탈퇴한 멤버에게 받은 피드백이 상세 정보로 들어가면 잘 보이지만 TableView에서 표시되지 않는 문제가 있었습니다.
그 문제를 해결하기 위한 PR입니다.
- TableView에서 피드백 정보 안보이던 문제 해결했습니다.
guard let으로 userName이 없다면 제한하고 있었는데, userName이 nil이라면 "탈퇴한 멤버" 가 표시되게 구현했습니다 !
- 지난 회고목록을 불러오는 함수의 이름이 dispatch로 되어있어서 fetch로 변경했습니다 !
나에게 피드백을 준 사람을 탈퇴시켜보면 됩니다... 하하
그리고 내가 받은 회고에서 확인하시면 됩니당 ^________^
https://user-images.githubusercontent.com/78677571/204478521-a225a459-2453-4415-a02c-360d090d7b1b.mp4
탈퇴한 멤버 라는 워딩이 나름 괜찮다 생각이 드는데, 다른 멤버들과 같은 UI를 가지는게 조금은 어색한 느낌이 드네요.
탈퇴한 멤버의 표시가 평소와 같은 UI가 아닌 다른 방식으로 표시되어야 할 것 같아요 !
- close #191
> [CHORE] 탈퇴한 멤버에게 받은 피드백 정보 안뜨는 문제 해결

- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
https://user-images.githubusercontent.com/59243274/204475827-cc743126-1b09-4cff-a241-0938b7b9c8ca.mp4
현재에는 세그먼트 컨트롤의 값이 변경 됨에 따라 Continue 목록 불러오기, Stop 목록 불러오기 2가지 API를 계속해서 호출하는 방식으로 구현이 되어 있었습니다. 그로 인해 테이블 뷰가 리로드 될때 버벅거리는 현상이 있었습니다.
제가 생각하는 이 버그의 문제는 2가지 였습니다.
첫째, 나의 회고 뷰는 이미 끝난 회고를 받아와서 그 중 Continue, Stop을 보여주는 뷰기 때문에 세그먼트 컨트롤이 바뀔때마다 API 통신을 하는것은 굉장히 바보같은 일이다. 
둘째, 버벅거림의 버그는 우리가 개발자로서 Continue와 Stop을 (세그먼트를) 막 눌러서 얘가 지금 reload 되지도 않았는데 다른걸 reload 하는 과정에서 생기는 부분같다.
첫번째 문제의 해결책으로 API 통신을 viewDidLoad에서 한번에 둘다 하고 Continue는 ContinueArray라는 배열에 Stop은 StopArray라는 배열에 담아두고 세그먼트가 바꼈을 때 각각의 배열을 사용하는것으로 처리했습니다. 
두번째 문제의 해결책은 사실 아직 고민중입니다. 
일단 메인 쓰레드 보장을 해줬고, 음.. 어떤 방식이 있을까요? (디퍼블..?)
----------------------------------------------
** 2022년 12월 1일 **
팀원들과 논의한 결과, 딸각거림은 새로운 이슈를 파서 해결하는것으로 하겠습니다. 
현재 …
> [FIX] 회고 디테일 뷰 API 분리

- Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
리더가 회고일정을 설정했음에도 homeView에서 바로 반영되지 않는 문제가 있었습니다.
회고 일정을 설정하는 request를 보냄과 동시에 해당 view를 dismiss해서 돌아가는 view에서 viewWillAppear가 돌아갈 때 해당 request가 반영되지 않아있는 문제였습니다.
API통신이 완료되었을 때 dismiss되게끔 순서를 보장해줬습니다.
API통신이 제대로 됐을 때 dismiss되게 변경했습니다.
새로 방을 만드시고 회고 일정을 등록해보시면 됩니다.
https://user-images.githubusercontent.com/78677571/204683093-a8ae26b5-0f0f-499a-8983-ec534e9a901c.mp4
지난번에 Alamofire에서 responseDecodable를 쓰기 애매한데 사용하는 경우에 대해 말씀드렸었는데, 현재 PR에선 if let 으로 return되는 데이터가 있다면 해당 코드를 실행하게 함으로써 순서를 보장해줬습니다. 
```swift
AF.request(type.address,
method: type.method,
parameters: type.body,
encoder: JSONParameterEncoder.default,
headers: type.header
)
.validate(statusCode: 200..<400)
.response { [weak self] json in
if let _ = json.value {
self?.dismiss(animated: true)
}
}
```
하지만 responseDecodable을 사용하지 않고 …
> [CHORE] 회고 일정 추가 후 dismiss되게 변경

- Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
팀을 생성하고 팀원 초대를 위해 초대코드를 복사했을 때, 토스트뷰가 뜨는데 계속 클릭하면 쭉쭉 내려가는 문제가 있었습니다.
https://user-images.githubusercontent.com/78677571/204723095-7ddc1624-15ec-4c3f-8f34-9d7ec51a3d32.mp4
1. 토스트뷰가 `isTappedCopyButton = false`일때만 보이게 조건을 걸어뒀습니다.
2. 토스트뷰가 보이기 시작할 때, `isTappedCopyButton`을 true로 바꿉니다.
3. 토스트뷰가 완전히 사라졌을 때 `isTappedCopyButton`을 false로 변경합니다.
++)
코드 복사하기 버튼이 좀 딱딱해 보여서 살짝 수정한 뒤 최고의 디자이너 선생님들께 어떤지 제안하려고 했는데, 저희 피그마엔 cornerRadius가 7로 되어있고, 실제론 4로 되어있어서 7로 반영했습니다.
새로 방을 만들려면 다시 회원탈퇴를 해야해서 SceneDelegate를 수정했습니다.
```swift
if isLogined {
rootViewController = UINavigationController(rootViewController: InvitationCodeViewController(teamName: "", invitationCode: "ABCDEF"))
} else {
rootViewController = UINavigationController(rootViewController: LoginViewController())
}
``` …
> [FIX] 초대코드 복사 토스트가 계속 내려오는 문제 해결

- Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
회고시간에 내 차례에 보이는 상세 피드백 화면에서, 내용이 길 때 스크롤이 되지 않아서 다 안보이는 문제가 있었습니다.
해당 부분을 손봤습니다.
UIStackView를 추가해서 내부 컨텐츠의 크기에 따라 유동적으로 사이즈가 바뀌게 수정했습니다 !
++)
불편한 줄이 있어서 살짝 띄어줬습니다 ! ^__________^
회고를 시작했을 때, 순서에서 날 선택하고 받은 피드백들을 보면 됩니다.
애매하다 싶으시면 SceneDelegate에서 
```swift
if isLogined {
rootViewController = InProgressDetailViewController(feedbackInfo: ReflectionInfoModel(nickname: "호야", feedbackType: .continueType, keyword: "메롱", info:
"""
ㅁㄴㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
ㅇ
d
d
d
d
d
d
d
d
d
d
d
d
"""
,
start: """
d
d
d
d
fs
d
fsd
f
sdf
sd
fds
f
sd
fs
d
f
ds
f
sd
f
sd
f
ds
f
sd
fsd
fsd
fs
"""
))
} else {
rootViewController = UINavigationController(rootViewController: LoginViewController())
}
```
이런식으로 첫 화면을 바꾸셔도 됩니다 !
https://user-images.githubusercontent.com/78677571/204770547-b9ec6f4a-b5df-4c90-a70f- …
> [CHORE] 디테일 상세보기 화면에서 스크롤 안되는 문제 해결

- README.md
맛도리 애플 레포지터리의 간판이 필요했습니다.
- 상단 Banner / Preview / Directory 이미지 제작
- 기능 설명 추가
- Tech & Skills / Development Environment / License 캡슐 추가
- Author 테이블 추가
레포 메인에서 브랜치를 feature/202-make-read-me 바꿔서 바로 확인하시면 됩니다!
project에 관한 내용을 추가할지 말지 고민이네요,,,
원래 코드/깃 컨벤션을 추가하려고 했는데 양식이 마땅하게 떠오르지 않아요,, 
아이디어 있으시면 의견 제안 부탁드립니다!
- close #202
> [ADD] README 만들기

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/KeywordView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
새로 기획한 내용중의 일부인 상세 키워드 UI를 변경하는 PR입니다.
내가 쓴 피드백 수정하러 가기전, 상세 화면이 보이는 부분에서의 키워드 UI를 변경했습니다.
HomeViewController에서 사용하는 키워드들의 enum 값을 사용했습니다.
보관함 탭에서 내가 쓴 피드백을 클릭해보시면 됩니다.
요기 왼쪽 아래부분의 corner값이 다르기 때문에 그런지, shadow가 살짝 다르게 들어가있는 듯한 느낌입니다.
현재 이 부분까지 수정하기엔 급한 상황이라, 공유만 드리고 넘어가겠습니다 !
수정하러 가기 버튼을 누르면 나오는 view에서는 이드가 작업하고있는 키워드 TextField를 가져와 사용할 예정입니다.
- close #217
> [ADD] 내가 쓴 피드백 상세 보기 화면에서의 키워드 UI를 변경했습니다.

- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
피드백을 추가하는 과정이 수정됨에 따라, start를 작성하는 부분이 자연스럽게 내용에 합쳐졌습니다.
그에따라 피드백 돌아보기 view를 수정하는 PR입니다.
1. 단순히 start 부분을 삭제했습니다.
2. 회고에 대한 정보를 model로 받아서 사용하는 부분이 변하지 않는데 `var`로 설정되어 있어서 `let`으로 수정했습니다.
지난회고에서 start가 있는 feedback의 view로 들어갔을때 start내용이 안보이면 됩니다 !
실제로 DB에 start가 있는데 view에선 표시되지 않습니다 !
지우기만하면 되서 아주 편했습니다 !
개꿀 ! ^________^
- close #225
> [CHORE] 피드백 돌아보기 view에서 start 내용 삭제

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackKeywordViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/UIComponent/KeywordTextFieldView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
피드백 수정하기 view에서 키워드 부분이 일반 TextField에서 키워드 TextField로 변경되었습니다.
그에 따른 PR입니다.
기존엔 AddFeedbackViewController와 EditFeedbackViewController의 모양이 비슷했습니다. 
그래서 AddFeedbackViewController를 상속받아서 사용하고 있었는데요, 피드백을 추가하는 부분의 UI도 변경되어서 더 이상 상속받아서 사용할 이유가 없어졌습니다.
1. 상속받아서 사용하는 부분들을 삭제하고 해당 viewController로 옮겼습니다.
키워드 TextField의 UI를 변경했습니다. @seongmin221 이 만들어준 UI를 사용했습니다.
기존에 PlaceHolder가 "키워드를 입력하세요" 로 고정되어 있어서, 처음 들어갔을 때
이렇게 어색하게 비어있는 상황이 생기더라구요 !
해당 키워드의 크기가 "키워드를 입력하세요" 이걸 기준으로 잡다보니 발생하는 문제였습니다. 그래서 그 부분을 현재 키워드로 수정하였습니다. 피드백을 추가하는 과정에선 "키워드를 입력하세요"가 제대로 들어가게 만들어 뒀습니다 !
2. 키워드 입력 UI를 수정했고
3. 키워드 TextField View를 수정했습니다 (네이밍 포함)
4. start 부분을 삭제했습니다.
보관함 탭에서 팀원에게 전달한 피드백을 수정해보시면 됩니다 !
https://user-images.githubusercontent.com/78677571/206691688-69b278ca-175a-472b-b5c7-28c3113933e0.mp4
상속을 받아서 사용할 때도 사실 …
> [ADD] 피드백 수정하기 UI변경에 따라 상속 삭제

- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
백로그의 '피드백이 없을 경우 키워드를 눌렀을 때 피드백 추가하기로 분기처리하기' 해결하기 위해 만든 이슈의 PR 입니다~
- keyword list 에 아무 피드백도 없을 때(첫 피드백을 작성.. 상태일 때) 피드백 추가 페이지로 이동
피드백 없을 때 키워드를 터치해주세요~
피드백 있을 때에는 토스트가 뜨고 없을 때에는 페이지가 뜨면 성공입니당
https://user-images.githubusercontent.com/72431640/209920158-ce1fd35b-ca94-4926-a702-0729fb7f74ab.mp4
- close #240
> [CHORE] 키워드가 없을 때 cell 터치하면 피드백 추가로 이동하기

- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
기존 디자인은 비교적 덜 중요한 라벨이 내용보다 눈에 띈다는 문제가 있어서,
라벨들의 글자 크기, 두께 그리고 전체적인 레이아웃을 수정했습니다.
- 라벨과 텍스트 font와 text color 변경
- 콘텐츠 레이아웃 변경
- Scroll 되는 영역 변경 (전체 -> 피드백 내용 영역만)
feature/237-new-my-reflection-feedback 브랜치로 오셔서
지난 회고에서 팀원에게 받은 피드백이 있다면, [나의회고 > 회고 선택 > 피드백 선택] 하고 보시면 됩니다!
만약 받은 피드백이 없으시다면, (계정이 다 달라서 없을 가능성이 있어요) DB에서 직접 피드백 하나 추가하셔서 보셔도 됩니다.
https://user-images.githubusercontent.com/81340603/209898183-16359445-c94d-4464-95dc-19f93c3b96fd.mp4
지금까지 주로 제가 만들어 온 뷰들은 다 ScrollView 를 포함하고 있었는데요.. 그때마다 레이아웃 조정하는데 항상 어려움이 있었습니다,,
이번에도 레이아웃이 잡히지 않아 원하는데로 스크롤이 안되는 문제가 계속 발생했는데, 약간의 고군분투 끝에 나름의 방법을 확실히 발견했습니다.
⭐️ 스크롤뷰를 사용한다면 꼭! 기억해야 하는 것 ⭐️
1. ScrollView는 스크롤의 영역을 잡아주는 역할입니다. 위 또는 아래에 위치한 일부 콘텐츠들을 fix 해두고 나머지 영역만 스크롤 하고 싶다면 그 영역을 제외하고 레이아웃을 잡아주어야 해요.
2. **세로 방향으로만** 스크롤하기 원한다면 ContentView를 …
> [ADD] 변경된 MyReflectionFeedback UI 구현

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/TextField/CustomTextField.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
JoinTeamVC와 관련된 자잘자잘한 버그 및 수정 사항들을 반영했습니다.
(날로 먹는 PR 입니다 ㅎ)
1. 잘못된 초대코드를 입력했을 때 나오는 Alert 문구 변경하기
2. JoinTeamVC의 textfield 를 눌렀을 때 올라오는 키보드 언어를 영문/대문자로 기본 설정하기
3. CustomTextfield의 border 색 변경하기
feature/244-chore-join-team으로 오셔서
JoinTeam 화면에서 잘못된 초대코드 입력해보고, 키보드 언어 확인해보시면 됩니다!
|<img src="https://user-images.githubusercontent.com/81340603/210201055-b00310ad-88f7-4005-a1fb-e5d75e22c41c.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/210201061-d60f9134-17a9-4c60-b2a5-d78071a35bb9.png" width=200px />|
|:---:|:---:|
|<center>영문대문자 키보드, textfield border</center>|<center>잘못된 초대코드 입력시</center>|
- 키보드 언어 설정을 위한 메소드를 viewDidLoad에 넣는 게 맞을까요? setupDoneButton 메소드와 비슷한 결이라는 생각이 들어서 일단 여기에 넣어뒀습니다!
- 키보드 언어 설정을 위해 JoinTeamVC > BaseTextFieldVC > CustomTextfield에 직접 접근해 …
> [CHORE] JoinTeamVC에 있는 버그 및 수정사항 반영하기

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
작업은 닉네임에 이모티콘을 포함하여 입력했을 때, '중복된 닉네임입니다'라는 생뚱맞은 Alert이 떴을 때부터 시작했습니다..
1. SetNickname에서 이모티콘을 입력했을 경우, "이모티콘 사용 불가능", "닉네임을 다시 입력해주세요." 라는 Alert 띄우기
2. Alert이 떴다면 JoinTeamVC로 화면 넘어가지 않도록 하기
3. 닉네임을 입력하고 앱을 종료할 경우, 재접속 했을 때 팀 합류 페이지 띄우기
아래 Review Note에서 상세하게 설명 드리겠습니다!
feature/242-no-emoji-on-nickname 로 이동하셔서
1. 회원 탈퇴 후 애플로그인 > 닉네임 설정 > 앱 종료 > 앱 재접속 테스트 = 팀 합류 페이지로 이동해야 함
2. 팀 합류 > 홈 > 앱 종료 > 앱 재접속 테스트 = 입력한 닉네임과 팀 이름이 각각 MyReflection과 Home 의 title label로 보여야 함
4. 로그아웃 > 애플 로그인 테스트 = 2와 동일하게 닉네임과 팀 이름이 각각 MyReflection과 Home 의 title label로 보여야 함
5. 회원 탈퇴 > 애플로그인 테스트 = 닉네임 설정 화면이 나와야 함
가능한,, 모든 경우의 수를 테스트 해주시면 감사하겠습니다 ,,
이모티콘이 포함된 닉네임을 입력했을 경우 [기존 화면, 구현 화면]
https://user-images.githubusercontent.com/81340603/210178321-1d3578e2-6ae2-4579-aa54-6791b112854e.mp4 …
> [CHORE] 닉네임에 이모티콘 들어가 있을 경우 Alert 띄워주기 + 추가 버그 해결

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewFlowLayout.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
백로그의 <리더의 경우 키워드 개수가 많아지면 키워드 마지막 줄이 가려지는 버그>를 해결하는 PR 입니다
- 리더의 경우 회고의 상태가 Setting Required 이면 키워드의 bottom을 회고 일정 설정하는 label의 top 에 둠
- 리더의 경우 회고의 상태가 Before 이면 키워드의 bottom을 피드백 추가 버튼의 top 에 둠
- 일반 멤버의 경우 키워드의 bottom을 피드백 추가 버튼의 top 에 둠
키워드 엄청 추가해야 하는 귀찮음이 있는데 제가 이거 추가해뒀습니다..!!
DB에 ㄹㄹㄹㄹㄹㄹㄹ 도배된 팀의 회고가 있는데 (팀: 72 / 회고: 160)
이 팀의 이 회고로 설정해서 확인해주시면 됩니다..!!
<리더 - 회고 일정 없을 때>
https://user-images.githubusercontent.com/72431640/210717147-32aa31e5-b51c-4b62-b587-da3c651ac67b.mp4
<리더 - 회고 일정 있을 때>
https://user-images.githubusercontent.com/72431640/210717315-b382c0dc-f972-4554-af2b-6a84a20a4fb4.mp4
<리더, 멤버 - 회고 시작 했을 때>
https://user-images.githubusercontent.com/72431640/210717430-eb296d09-08cc-40f2-857f-b56a3dc2df2a.mp4
<멤버 - 회고 일정 있을 때 없을 때 똑같음> …
> [BUG] 리더의 경우 키워드가 잘려서 보이는 버그 해결

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
백로그 [팀이름에 특수문자 입력하지 못하도록 핸들링하기](https://www.notion.so/46db2c7220b949b1b3bad4ba796dcbbe) 을 해결한 PR 입니다. (aka 날먹)
- Alert 문구 변경 (특수문자를 사용할 수 없습니다. / 팀 이름을 다시 입력해주세요.)
- TextLiteral 로 text 이동
feature/258-no-symbol-on-team-name 으로 오셔서,
팀을 생성하는 화면에 'oh!'를 입력해보시면 얼럿이 뜨는 걸 확인하실 수 있습니다!
`oh!`를 입력했을 때 위와 같이 얼럿이 뜨는 것을 확인할 수 있습니다!
- close #258
> [CHORE] 팀이름에 특수문자 입력하지 못하도록 핸들링하기

- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectMemberView.swift
위 스크린샷에서 보이듯 총 3가지의 UI 수정사항 변경과 1개의 버그해결의 PR입니다. 
1. MemberCollectionViewCell 의 색 white 100 으로 변경 (UI 수정사항 변경)
2. 피드백 맴버 & 종류 Container 색 white 200으로 변경 (UI 수정사항 변경)
3. 피드백 맴버 컬렉션 뷰 셀 높이 조정 (UI 수정사항 변경)
4. 맴버가 5명 이상일 경우 최하단 CollectionViewCell이 가려지는 버그 해결 (버그해결)
1. 현재 구현에서는 멤버 라벨의 색이 white300으로 설정되어 있는데 이는 회고 중일 때와 UI가 다르기 때문에 white100으로 분기처리 해줬습니다.
2. 1번과 마찬가지로 회고전에 피드백 추가 상황일때와, 회고중 피드백 들을 맴버 선택의 분기처리로 해결했습니다.
3. 셀 높이 수정은 Review Note에서 자세히 설명하겠습니다.
4. 가려지는 버그 해결도 ReviewNote에서 자세히 설명하겠습니다.
feature/262-change-color 로 오셔서 피드백 추가하기를 눌렀을때 UI를 보시면 됩니다. 
1. 피그마 UI와 같은지
2. 5명이상일때도 아래가 잘리지 않는지 확인해보시면 됩니다.
| 1,2,3| 4 |
| ---| --|
|
먼저 사실 1,2,3 번과 4번의 같은 이슈가 아니였습니다. 그런데 3번을 보다보니 4번이 해결되면 자연스레 해결될것이라고 생각이 들어서 해결하다 보니 4번 이슈가 이 PR에 포함이 되었습니다. 
현재 MemberCollectionViewCell에 memberShadow라는 그림자를 만드는 …
> [CHORE] 피그마와 다른 UI/색 수정하기, 멤버가 5명 이상 되는 경우 멤버 최하단 CollectionViewCell 이 가려지는 버그 해결하기

- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
피드백을 줄 맴버를 터치하면 바로 종류 영역이 드롭다운 되는 형식으로 변경하였습니다! (현재는 아니였음)
맴버 선택 시 바로 드롭다운
feature/265-drop-down 로 오셔서 피드백 추가하기 부분에서 눌러보시면 됩니다.
https://user-images.githubusercontent.com/59243274/211203228-4065587c-a126-4001-9a34-2201f32c4e9d.mp4
원래는 didSelectedMemeber 클로저에서 작업하지 않고 새로운 클로저를 열어서 연결했었는데 아무래도 같은 동작(맴버를 선택한다) 에 액션이 2개인 거라 그냥 didSelectedMemeber 클로저에 합쳤습니다. 괜찮나요?
- close #265
> [CHORE] 멤버를 터치한 후 피드백 종류 drop down 되도록 하기

- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Network/Model/Keyword/Keyword.swift
- Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
- Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
백로그의 <눌렀던 피드백 상태를 저장해서 다른 뷰에 다녀와도 그 상태가 유지되도록 구현하기> 에 대한 PR 입니다!
- 눌렀던 피드백인지 아닌지 UserDefaults에 저장 -> `seenKeywordList`
- InProgress 에서 키워드 불러올 때 UserDefaults에 저장한 값으로 키워드 스타일 변경
- "모든 회고 끝내기" 버튼 누르면 UserDefaults에 저장한 값 삭제 -> `clearSeenKeywordIdList`
현재 진행중인 회고에 들어가서 아직 확인하지 않은 키워드를 누르고 앱을 껐다 키든 회고에서 나갔다 들어오든 해보세요!
<누른 피드백 상태 저장되는 영상>
https://user-images.githubusercontent.com/72431640/211263312-e728955e-d259-4a2f-be01-9c7e9ebb7eec.mp4
<모든 회고 끝내기 누르면 reset 되는 영상>
https://user-images.githubusercontent.com/72431640/211263496-ec6cf1f3-4385-42ca-898e-912c2103e756.mp4
키워드를 누른 상태를 어디에 어떻게 저장할까 하다가 UserDefaults가 적당하다고 생각했습니다..!!
더 좋은 방법이 있다면 알려주세요 ><
그리고 확인한 키워드 id 를 list가 아닌 set으로 할까 했는데 (왜냐하면 중복 확인하는 과정이 없어질 것 같아서..!)
좀 익숙하지 않은 set을 사용하려니 오류가 자꾸 생기더라구요🤔
set으로 하길 원하신다면 바꿔보겠습니다!
(뭐가 더 좋은 방법인지는 잘 …
> [ADD] 눌렀던 피드백 상태를 저장해서 다른 뷰에 다녀와도 그 상태가 유지되도록 구현하기

- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
저와 @dangsal , @MMMIIIN 이 작업할 수 있도록 우선적인 부분 먼저 만들었습니다!
현재 (아마) 회고가 진행중이 아니더라도 아래 View 처럼 보일겁니다!
회고 진행 상태에 따라 저 버튼 UI 가 바뀌는건 다음 PR 에서 다루겠습니다!
- HomeView 상단 바뀐 UI 우선 적용
- 적용시키기 위한 최소한의 코드 변경 적용 -> 삭제한 코드들이 꽤나 있음
제 브랜치로 오셔서 HomeView 확인해주세요!
회고 상태가 어떻든 파란색 JoinReflectionButton 이 띄워져 있는데 오류 아니고 아직 작업을 안해서 그렇습니다!
- 뭔가 시뮬레이터와 앱에서 보니까 팀 이름이 조오오오오금 작은 것 같기도 하구요...🤔
- 요 PR 올리고 JoinReflectionButton과 그 외의 부분들도 작업하겠습니다!
- close #275
> [ADD] HomeView 상단 바뀐 UI 우선 적용

- Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
개발과 배포를 용이하게 하기 위해 개발용 서버와 배포용 서버를 메리가 분리해주었습니다.
이를 반영한 피알입니다.
- 개발용 서버 주소로 변경 (3000 -> 3001)
없습니다. 코드만 확인하시면 돼요!
- close #286
> [CHORE] 개발용 서버로 변경

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/JoinReflectionButton.swift
팀을 필수로 합류할 필요 없이 건너뛰기 하는 경우, homeview의 UI를 구성하는 PR 입니다
- teamButton '팀 없음' 으로 설정
- joinReflectionButton 비활성화
팀이 없는 상태에 SceneDelegate에서 바로 homeVC로 넘어가도록 설정해주세용
slack에도 올렸듯 constraint 가 깨지는 부분이 있습니다..! 요 부분 addFeedback의 preview 담당하시는 분이 해주시면 감사하겠습니다 ^__^
자세한 사항은 slack 매크로 참조..
reflectionStatus enum에 preview를 추가하면 좋은데..! 그러면 api 도 다 변경해야 하기 때문에 그냥 리뷰에 남긴 것처럼 isPreview라는 입력값을 하나 더 줬습니다..!
더 괜찮은 방법 있다면 알려주세요 ><
- close #297
> [ADD] 건너뛰기 용 homeVC 편집

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
간단한 피알입니다 ㅎㅎ
팀 합류, 프로필 설정 없이도 앱을 둘러볼 수 있도록 JoinTeam에 건너뛰기 버튼을 추가했습니당
간단하게 '건너뛰기' 버튼을 nav bar에 추가하고
button에 HomeVC로 넘어가는 액션을 추가했습니다! 룰루
feature/309-finish-setup 으로 넘어가셔서 팀합류 되어 있는 경우 > 탈퇴 부탁드리고 팀합류가 안 되어 있다면 애플로그인 후 JoinTeam에서 확인!
- close #309
> [ADD] JoinTeam - 건너뛰기 버튼 추가

- Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/MainButton.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
현재 <회원가입>, <팀 생성>, <팀 유효한지 확인> 요 페이지들이 로딩이 꽤 오래 걸리는 것으로 알고 있습니다
그래서 로딩하는 중임을 표기하기 위해 loading indicator 을 추가해뒀습니다
지난번 회의에서 말한 것 처럼 옳은(?) 방법으로 추가해둔 것인지 잘 모르겠어서
같이 한 번 생각해보면 좋을 것 같아요 ~~
<팀 참여 후 프로필 생성까지>
https://user-images.githubusercontent.com/72431640/227869184-ccc47500-ccdb-45be-bd47-3c0cc0f27a1a.mp4
<팀 생성 후 프로필 생성까지>
https://user-images.githubusercontent.com/72431640/227869541-bb53842a-b79b-409a-a74f-30c7b49fa702.mp4
- 팀 참여 페이지 loading indicator 추가
- 팀 생성 페이지 loading indicator 추가
- 프로필 페이지 loading indicator 추가
제 브랜치에서 탈퇴한 뒤 프로필 생성 해보세요!
아마 UserDefaults 문제일 것 같긴 한데, 팀 생성하여 팀 참여 시 '팀 없음'이 나오게 됩니다,,,
요 버그는 어차피 제 담당이라 제가 해결해볼게요!
- close #323
> [CHORE] loading indicator 추가

- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
자신에게 피드백 줄 수 있는 상황을 없애기 위한 PR입니다.
| 이전 | 이후 |
| ----|-----|
| <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/59243274/753bc509-1ab7-44b1-a266-51f6c60ea2a7" width = "350">      |      <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/59243274/9e952b71-ac5d-4cce-af60-5fc0c5249915" width = "350">    |
기존 members는 팀에 속한 팀원들을 전부 다 데려오는 방식이어서 
membersExceptMe 라는 변수를 userId 를 비교해서 제거한 리스트로 정의하고 그 리스트를 넘겨줍니다.
feature/363-bugfix 여기로 오셔서 피드백 추가를 눌렀을 시 자기 이름이 뜨나 확인하시면 됩니다.
- close #363
> [BUGFIX] 자신에게 피드백 줄 수 없도록 수정

- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyFeedbackView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
현재 MyFeedbackVC 의 EmptyView 가 중앙정렬이 안되어있는 상태인데,
고놈 정렬 했습니다!
- 무지성 너비 값으로 위치 잡던 코드를 없애고 원인을 찾았습니다 하하
가운데 정렬이 되어있지 않은 이유가 저 왼쪽 inset 때문인데요,
`insetForSectionAt` 으로 데이터가 없을때 inset을 없도록 만들었습니다!
아무나 피드백 없는 사람을 확인해주세용
- close #369
> [CHORE] MyFeedbackVC Emptyview 중앙정렬

- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
팀 없음 상태일 때 팀을 알려주는 레이블의 chevron 간격이 너무 좁았습니다!
그래서 간격을 넓히는 pr 입니닷
띄어쓰기 하나.. 추가...
팀 없는 상태로 와 주십쇼
- close #373
> [CHORE] 팀 없음 옆 chevron 에 간격 추가

- Maddori.Apple/Maddori.Apple/Network/EndPoint/TeamDetailEndPoint.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
프로필 수정에서 프로필 이미지 외 닉네임 또는 역할을 수정할 경우 
프로필 이미지가 삭제되는 문제를 해결했습니다.
메리께서 기존에 put 이었던 method를 post로 고쳐주셔서 아주 쉽게 버그를 잡을 수 있었습니다~ (땡스투 메리)
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/81340603/fcd51ffa-f804-424f-a4cf-e4966851b963
근데 이제 이드가 말했던 오류가 떠요
셀 재사용의 문제인듯 보입니당 ㅎ
put을 patch로 변경하였습니다!
feature/378-resolve-image-disappearence으로 이동하셔서
프로필 닉네임 수정 해보시고, 그 다음에는 프로필을 수정해보세용!
- close #378
> [BUGFIX] 이미지 변경하지 않으면 이미지가 사라지는 문제 해결

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
v2.0.0 심사 리젝사유로 카메라와 사진에 접근하는 메시지가 빠져있어서 추가하는 PR입니다.
info.plist에 접근 문장을 추가했습니다.
`feature/389-camera-access-message` 브랜치로 오셔서 앱을 삭제하시고 다시 돌려서 접근 권한 Alert을 확인하시면 됩니다.
UXWriting에 대해 더 나은 방법이 있다면 알려주시면 감사하겠습니다.
- '키고'가 프로필 사진 설정을 위해 사용자의 사진에 접근하려고 합니다.
- '키고'가 프로필 사진 설정을 위해 카메라에 접근하려고 합니다.
- close #389
> [CHORE] 카메라, 사진 접근 메시지 추가
