DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Extension/UITextField+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CloseButton.swift
- Maddori.Apple/Maddori.Apple/Screen/AddReflection/AddReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/AddReflection/UIComponent/ReflectionNameView.swift
- Maddori.Apple/Maddori.Apple/Screen/Main/MainViewController.swift
새로운 회고를 추가하는 View를 만들었습니다.
텍스트필드의 상태에 따라 메인 버튼이 활성화되는 문제는 새로 이슈를 파서 작업하도록 하겠습니다. 현재는 UI를 위주로 작업했습니다 !
모달이 올라오는 것 부터 구현해야 할 것 같아서 메인화면의 버튼에 present를 걸어두었습니다 ! 추후에 메인뷰 작업하시는 분이 트리거가 되는 view를 만들어주실 때 수정해주시면 감사하겠습니다 !
13번 브랜치로 실행하고 메인버튼 누르면 이동되게끔 일단 만들어뒀습니다 !
https://user-images.githubusercontent.com/78677571/196464925-cf686e18-bd56-466d-a900-b5b23a558374.mp4
**UIDatePicker가 크기마저도 커스텀이 안되는 것 같아서 디자인 수정이 필요해 보입니다 !** @Guel-git @seongmin221 
현재 레이아웃도 영역들이 이상하게 잡혀요..
텍스트 필드에서 글자가 이상하게 바뀌는 문제는 @dangsal 의 도움을 받아 해결해보도록 하겠습니다.
++ 생각보다 파일체인지가 많고, 절대적인 코드가 많아서 리뷰하는데 불편함이 있을 것 같습니다. 다음번엔 최대한 PR을 나누는걸 UI를 그리는 작업에도 적용해야겠습니다. 
- close #13
> [ADD] 새로운 회고 추가하기 View 생성

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Base/BaseCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Global/Base/BaseTableViewCell.swift
- Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/BackButton.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CloseButton.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/AddFeedbackMember/AddFeedbackMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/AddReflection/UIComponent/ReflectionNameView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
현재까지 개발하면서 주석의 순서나 스토리보드 init과정의 fatalError에 대해 얘기가 나온것들을 같은 맥락으로 통일시켰습니다 !
파일체인지가 꽤 있지만, 대부분 순서만 수정한거라 긴장안하셔도 됩니다 !
- fatalError -> nil 로 변경
- 주석 순서 설정
빌드가 정상 동작하고 모든 viewController들이 잘 불립니다 !
- UIComponent들을 폴더링 해야하는데 지난번에 이드의 컨플릭트 이슈가 있었어서 최대한 merge가 된 시점에 정리하겠습니다
- 네비바에 들어가는 버튼들의 frame 설정을 init하는 과정에서 frame을 정할것인지 auto layout으로 정할것인지에 대한 문제는 mainButton의 Gradient문제를 어떻게 해결하느냐에 따라 달라질 것 같아서 우선 뒀습니다.
- close #33
> [CHORE] 코드 스타일 통일

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/FromTo/FromToViewController.swift
현재 피드백 줄 사람을 입력해주세요 뷰에서 From 이 To 보다 먼저나오는것이 순서상 맞지 않다고 생각합니다.
저희 편지를 쓸때를 예로 들면, 진저에게, 호야가 순서로 To, From 순서 입니다. 자연스럽고 이미 유저 경험이 많이 쌓인 저 순서가 좋을 거 같다고 판단했습니다.
- From 과 To의 위치 변경
- 플레이스 홀더 한단어 -> 키워드로 변경
57번 브랜치롤 오셥쇼!
- close #57
> [FEAT] From To 위치 변경

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/AddReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyBoxMemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
테플 이후에 개발하기로 했던 뷰를 개발하기 시작했습니다. 
| 전체 View | 작업 한 부분 |
|---|---|
|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199454861-43c6a19f-f5e9-4a84-a4c2-6800ee12fc44.png">|<img width="404" alt="image" src="https://user-images.githubusercontent.com/78677571/199455888-989758c1-8736-4c12-a7c0-cda37a82073d.png">|
추가적으로 그림자를 조금 더 간편하게 만들어주는 extension을 추가했습니다 ! 그림자를 추가할 때 마다 4개의 값들을 설정해줘야하는데, 꽤나 번거롭고 헷갈리기도 해서 간편한 extension을 만들어두었습니다 ^________^
feature/65-mybox-title 브랜치로 오셔서,
SceneDelegate의 rootViewController를 MyBoxViewController 로 변경해주세요 !
해당 셀들을 눌러봤을 때 테두리와, 글자색, 그림자가 잘 변하는지 확인하시면 됩니다 !
https://user-images.githubusercontent.com/78677571/199457056-86a3f012-ad42-4283-8d76-3f2241d9608d.mp4
| Figma | 만든 View |
|---|---|
|<img width="297" alt="image" …
> [ADD] 보관함 View 팀원 선택 CollectionView 추가

- Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/Cell/MyFeedbackCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/TotalReflectionCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailTableViewCell.swift
#85 PR을 머지하면서 생긴 컨플릭트가 반영이 안됐습니다...!
그 컨플릭트 해결한 걸 포함시킨 PR입니다!
많이 달라지는 부분은 없습니다~
컨플릭트 해결
-
- close #74
> [CHORE]  #85 PR에 미반영된 컨플릭트 반영하는 PR

- Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
- Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/TabBar/CustomTabBarController.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackContent/AddFeedbackContentViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackMember/AddFeedbackMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/AddReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/HomeView/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Login/LoginViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/EditFeedbackFromMe/EditFeedbackFromMeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/FeedbackFromMeDetail/FeedbackFromMeDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/MyBoxViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/UIComponent/MyFeedbackCollectionView.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/FeedbackToMeDetail/FeedbackToMeDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/MyReflectionMainViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
API연결 작업 이전에 전체적인 View연결을 했습니다.
전체적인 App Flow를 연결했습니다. 데이터를 전달하는 부분은 API연결 과정에서 수정이 분명이 생길 것 같아 flow연결 위주로 작업했습니다 !
SceneDelegate의 `isLogined`를 false 와 true로 변경해서 실험해 주세요 !
https://user-images.githubusercontent.com/78677571/201662097-3931672d-a710-4a22-8f18-a601ef18e90e.mp4
https://user-images.githubusercontent.com/78677571/201662230-c8fba795-6a20-4e7f-9e93-fda1251700d5.mp4
https://user-images.githubusercontent.com/78677571/201662243-644a4799-a9c3-41d4-bef5-d1a5f803b32e.mp4
- 현재 보관함 탭에서 셀을 탭 했을때 보이는 뷰에서 버튼쪽 레이아웃이 탭바 아래로 사라지는 문제가 있습니다. 해당 부분 수정부탁드립니다 ! @Guel-git 
- 곳곳에 mark: - setup으로 적어둔 부분이 있는데 버튼에 들어가는 액션들을 프로퍼티 생성단계에서 설정하는 방식이 아니라 setup 부분을 baseViewController에 추가해서 setup 부분에 다 모아서 처리하면 좋을 것 같다 생각했습니다.
- 아까 얘기해주신 AppDelegate부분에 루트뷰를 설정해야하는 방식은 iOS13이전까지의 방식이고, 그 이후로 SceneDelegate가 생기면서 …
> [FEAT] 전체적인 App Flow 연결

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- API 통신에 있어서 조금 더 편하게 작업하기 위해 Alamofire Third party를 사용하기 위해 라이브러리를 추가합니다. 
- Alamofire 추가
TestFlight 버전에서 URLSession을 사용했는데, 꽤나 장황하게 코드를 작성했어야 하는 부분이 불편해서 alamofire를 사용해보려 합니다.
- close #106
> [CHORE] Alamofire 추가

- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
현재 진행중인 회고나, 완료된 회고 같은 데이터가 DB에 없는데, 편하게 추가하고 삭제하기 위해 모두의 시뮬레이터나 휴대폰에 앱을 세팅하기 위함입니다.
뭔가 userId값들을 사용하는 과정에서 순서상의 문제가 있어서 원하는대로 동작을 하지 않았습니다. 그 부분의 순서를 조금 수정해서 문제를 해결했습니다. 현재 endpoint들에서 userId를 매개변수로 받아서 사용하고 있었는데, 그럴 필요가 없고 userDefault에서 받아서 사용하면 되는 문제라 그 부분을 수정했습니다.
feature/130-dbtest-flow 브랜치로 오셔서 SceneDelegate의 수정이 필요합니다.
우선 첫 번째 실행때 방 참가나, 방 생성을 먼저 합니다
```swift
UserDefaultHandler.clearAllData() // <<<< 이 부분 추가
let isLogined = UserDefaultStorage.isLogin
var rootViewController: UIViewController
if isLogined {
rootViewController = CustomTabBarController()
} else {
rootViewController = UINavigationController(rootViewController: LoginViewController())
}
```
위의 UserDefault부분을 다 삭제하는 코드를 추가한 뒤 Run 해주세요 !
그리고 Home화면까지 가서 방 제목이 잘 뜨는 걸 확인한 후에 Run을 멈춰주시고,
```swift
// …
```
> [CHORE] DB에서 테스트하기 위해 초반 flow를 다듬었습니다.

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/String+Extension.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/CreateReflectionEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Response/AddReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/UIComponent/ReflectionNameView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
updateReflectionDetail API 연결하고 view와 연결도 해놨습니다!
- updateReflectionDetail API 작성
- view에서 설정한 값으로 DB에 올리기
DB에서 현재 회고가 없는 상태로 만들고 일정 생성하면 됩니다!
https://user-images.githubusercontent.com/72431640/202850417-c4a9dcb8-b8d3-4018-9066-45a2c37793ea.MP4
노션 백로그에도 작성해두긴 했는데, 키보드가 저절로 올라오고, 그 뒤로 다른곳을 터치해도 내려가지 않습니다..!!
P2로 고쳐야 할 버그라고 생각했어요..!
- close #139
> [FEAT] updateReflectionDetail API 연결 및 view 적용

- Maddori.Apple/Maddori.Apple/Network/Response/AllReflectionResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
나의회고 부분에서 API 연결 후 View에 올리는거 까지 완료했습니다.
1. AllReflectionResponse 의 구조를 변경했습니다. (한 Depth가 더 있다는걸 하루종일 인지하지 못했습니다. 심지어 Mary가 말해줬음에도 몰랐습니다....)
2. 데이터 View에 연결 (데이터 타입이 [[ReflectionResponse]?] 이 됨에 따라 잘 불러와지지 않았습니다.<- 이게 일요일을 다 차지했네요...)
나의 회고 탭을 누르면 VSCode에서 Done 이 된 것들이 잘 나오는지 확인하시면 됩니다.
현재는 3개가 회고 종료되어 3개가 뜹니다.
제가 진짜로 주말에 놀지 않았습니다. 그런데 API연결이 일단 서툴렀고, API Response가 잘못된걸 인지하지 못했습니다... 그래서 다른게 잘못된지 알고 별거별거 다 찾아보고 바꿔서 해보느라.. 매우 시간이 오래걸렸습니다. 그런데 @MMMIIIN 가 Response가 잘못되었다는것을 확인해줬고.. 해결되어 쏴악 연결하려 했으나.. 데이터 타입이 [[ReflectionResponse]?] 이 됨에 따라 잘 불러와지지 않았습니다.하하.. 제가 원하는 reflectionName, date 에 접근하려면 너무나도 이상하게 접근해야해서 그거 하느라 일요일을 또 날렸네요..
그리고 가 다음 페이지인 
은 어렵지 않게 작업하겠다 싶었는데 현재 작업한 뷰에서 reflectionId를 넘겨줘야 가능할 듯 합니다. 왜냐하면 다음 뷰는 현재 뷰에서 선택한 회고를 전달하고 그 회고에서 받은 피드백을 보여주는 페이지니까요..! 그래서 API가 수정되어야할것 같습니다. 현재 …
> [FEAT] 나의 회고 API 연결 후 데이터 올리기까지 완료

- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
나의 회고에서 특정 회고를 눌렀을 시 그 회고에서 받은 피드백들이 있는 디테일 뷰로 넘어갈때 API 연결을 했습니다.
** 이전 피알 머지 후 보시면 좋겠습니다. **
- 회고 id 넘겨주기
- 회고 이름 넘겨주기
- 회고 디테일 APi 통신
- 회고 디테일에서 받아온 데이터 뷰에 뿌려주기
신 델리게이트를 
```swift
guard let windowScene = (scene as? UIWindowScene) else { return }
window = UIWindow(windowScene: windowScene)
UserDefaultHandler.clearAllData()
UserDefaultHandler.setUserId(userId: 1)
UserDefaultHandler.setTeamId(teamId: 1)
UserDefaultHandler.setIsLogin(isLogin: true)
UserDefaultHandler.setNickname(nickname: "Mary")
let isLogined = UserDefaultStorage.isLogin
var rootViewController: UIViewController
if isLogined {
rootViewController = CustomTabBarController()
} else {
rootViewController = UINavigationController(rootViewController: LoginViewController())
}
window?.rootViewController = rootViewController …
```
> [FEAT] 나의회고 디테일 뷰 API 연결

- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
나의 회고에서 특정 회고를 눌렀을 시 그 회고에서 받은 피드백들이 있는 디테일 뷰로 넘어갈때 API 연결 이후 상세 내용으로 넘어가는 부분 작업입니다.
** 이전 피알 머지 후 보시면 좋겠습니다. **
- 데이터 모델을 수정했고, 넘겨줬습니다. 
- 그리고 뿌려줬습니다 ㅎㅎ
회고에서 받은 피드백을 눌렀을 때 잘 나오면 됩니다 ㅎㅎ
|디테일|상세|
|-------|------|
| <img src = "https://user-images.githubusercontent.com/59243274/203004416-e56d6f68-5979-4390-8b79-69aa573de9a6.png" width = "350"> | <img src = "https://user-images.githubusercontent.com/59243274/203003975-40564f3f-8e53-44cf-b746-fcb17bbd7500.png" width = "350">|
메리 그녀는 뭘까?
- close #155
> [FEAT] 나의회고 디테일 뷰 API에서 데이터 넘기기

- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/Cell/MyFeedbackMemberCollectionViewCell.swift
백로그에 <닉네임이 5글자 이상 될 때부터 잘리는 현상 해결하기> 문제를 해결하기 위한 PR 입니당
setMemberName 함수 변경
MyFeedbackViewController 의 memberList를 4글자 넘는 멤버로 바꿔보세요!
3번째 글자부터 자를 때
["홀롤", "홀롤롤", "홀롤롤롤", "홀롤롤롤롤"]
4번째 글자부터 자를 때
["홀롤롤", "홀롤롤롤", "홀롤롤롤롤"] 을 넣었을 때의 모습입니다
기존에는 2글자 넘어가면 ..으로 바뀌었는데 
3글자도 괜찮아 보여서 3글자일 때도 후보로 남겨봤습니다
뭐가 좋을지 알려주세요~~
- close #148
> [CHORE] 닉네임 3글자 넘어갈 시 ..으로 바꾸기

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/View/LabelButtonView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
자잘자잘한 버그들을 수정하기 위해서 작성한 PR입니다
1. 팀 생성 후 시작하기 View 에서 뒤로 가기 버튼 삭제하기 > 뒤로 갈 수 없어야 함
2. LabelButtonView 버튼에 색 적용하기 > 지금은 SystemBlue 컬러
3. 팀 멤버 수가 처음에 반영되지 않는 에러 해결하기
4. 에러 Alert UX Writing 반영하기 > '다람쥐' 제거 (다른 에러 핸들링은 PR 따로 남기겠습니다!)
5. TextLiteral UX Writing 수정하기 > . 제거
feature/170-small-bug-fix 로 오셔서 SceneDelegate 에 UserDefaultHandler.clearAllData() 넣어주시고 전체 플로우 한 번 테스트 해주시면 감사하겠습니당 !
|<img src="https://user-images.githubusercontent.com/81340603/203713611-9f3da530-b009-4f15-90ea-580e986edbef.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/203713672-187d2712-620c-4876-96c2-386f0e6c2b78.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/203708886-8e949415-d33d-48bb-9421-7aec6628eb92.png" width=200px />|
|:---:|:---:|:---:| …
> [FIX] 자잘자잘한 버그 수정하기

- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/UIComponent/ReflectionNameView.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
현재 리더가 회고 종료버튼을 눌러서 정상적으로 종료가 되었음에도 화면에 표시가 되지 않는 문제가 있었습니다.
이 문제가 리더에게 혼란을 줄 수 있다 생각이 들었고, 이를 수정하기 위한 PR입니다 !
https://user-images.githubusercontent.com/78677571/204959984-8d58a5c9-f063-4633-a167-7d90b7e74a48.mp4
회고가 시작되었다는 popup View가 뜨고 시작하기 버튼을 눌러서 시작하는 화면으로 넘어갔을 때 까진 문제가 없습니다.
정상적으로 회고를 마치고 회고 종료버튼을 눌렀을 때 원래 떠있던 view(아래의 사진)가 dismiss되는데, 
그때 회고를 시작하기 위해 보였던 popup View가 아직 떠있습니다.
이로인해 HomeViewController에서 viewWillAppear이 실행되지 않습니다.
제가 생각한 이유는 
곰곰히 생각해보니 회고 시작하기 버튼을 눌러서 회고를 진행하는데, 종료가 된 이후에도 시작하기 popup이 떠있는게 어색했습니다.
이 문제가 해결되면 자연스럽게 회고가 종료되었을 때 homeViewController에서 `viewWillAppear`이 실행되기 때문에, 새로운 회고에 대한 정보들이 적용될 것입니다.
그래서 시작하기 버튼을 눌렀을 때 해당 popup View가 dismiss되고 다음 화면으로 push 되게 해야겠다 라고 생각했습니다.
dismiss를 한 뒤 completion 부분에서 `push`를 하면 현재 view가 `dismiss`되었기 때문에, 새로 present를 할 수가 없습니다 !
그래서 …
> [CHORE] 리더가 회고를 종료하더라도 Home 화면에 반영되지 않는 문제 해결

- README.md
급하게 리드미를 작성해서,,, 디테일을 놓쳤습니다,,
앞으로 꼼꼼하게 확인해서 피알 올리겠습니닷,,
제보해주신 케미 감사합니다! (날먹 피알)
- Author 링크 변경
- Author 순서 변경 (ABC 순서대로)
- Server Repository 이미지 변경
레포 메인에서 feature/213-update-readme로 브랜치 이동하셔서 Author 쪽 확인해보시면 됩니다!
- close #213
> [CHORE] README 수정

- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
쇼케이스 리허설에서 "회고 중 homeview의 cell 터치 시 왜 아무 일도 안일어나냐"라는 피드백이 있었기에
회고 중 homeview의 cell 터치 시 selectFeedbackMemberVC 로 이동하도록 했습니다
- 회고 중인 경우 cell 터치 시 selectFeedbackMemberVC 띄우기
회고 시간이 된 팀으로 들어가 cell을 터치해보세요!
https://user-images.githubusercontent.com/72431640/206398921-b7ff1fd9-05d6-4ceb-a11d-ec88772a28d4.mp4
- close #223
> [CHORE] 회고 중 homeview cell 터치 시 selectFeedbackMemberVC

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
v1.3에 따른 develop 브랜치를 업데이트 합니다.
> [CHORE] v1.3에 따른 develop 브랜치 업데이트

- Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
백로그의 <폰트 크기 및 배치 변경된 거 반영하기> 에 해당하는 PR 입니다!
- @Guel-git 이 만들어둔 `MyReflectionFeedbackViewController` 에서 코드 복붙..
진행중인 회고의 아무 키워드나 눌러보시면 됩니다!
그냥 코드 복붙 말고 상속... 하는게 더 나을까 생각해봤는데
일단은 후딱 하기 위해 코드 가져다가 썼습니다..!!
정말 다를게 거의 없어서 상속이 낫다고 보시면 바꿀게요!!
- close #271
> [ADD] 새로운 디자인의 InProgressDetailVC 구현

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/UIButton+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
v1.3.1 이후로 추가로 생긴 팀 정보 수정하는 화면을 구현합니다.
그 중에서도 제일 상단 부분인 팀 이름과 편집 버튼을 만들었습니다.
PR을 최대한 쪼개서 리뷰하는 분들의 부담을 덜고자 함입니다 !
- 팀 이름과 편집 버튼을 구현했습니다.
1. 버튼은 현재 action까지만 넣어뒀습니다.
2. UIButton의 UnderLine을 위한 Extension을 만들었습니다.
`feature/282-team-edit-title` 브랜치로 오셔서
위 사진과 같이 버튼을 눌러보시면 해당 뷰로 이동할 수 있습니다.
|피그마|구현화면|
|---|---|
|<img src="https://user-images.githubusercontent.com/78677571/214521806-6f94c319-d1e9-4683-89c5-91338e66d2f2.png" width="300">|<img src="https://user-images.githubusercontent.com/78677571/214525621-12fd74a6-a920-4c91-b045-047723d55ddc.png" width="300">|
탭바를 사라지게 하는 방법에 대해서 의견을 구하고 싶습니다 !
제가 원한 방식은 (아래 영상의 탭바 부분을 주목해주세요 !)
https://user-images.githubusercontent.com/78677571/214526405-441a21d3-cb85-4f82-8971-20b73c50930c.MP4
당근마켓 앱처럼 설정 버튼을 눌렀을 때 새로운 view가 위로 추가가 되는 느낌이 확실한데, 제가 구현한 방식은 …
> [ADD] 팀 정보 수정 화면 상단 타이틀 구현 (1/4)

- Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
- Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/JoinReflectionButton.swift
새롭게 바뀐 HomeView UI의 JoinReflectionButton을 수정했습니다!
그에 따른 action들도 추가했어요!!
- 회고 상태에 따라 버튼 상태 변경
- HomeVC 코드 약간의 리팩토링
- JoinReflectionButton 상태에 따른 action 변경
- 아무 팀이나 참여하고 회고 막 해보세요!!
<SettingRequired ~ Before>
https://user-images.githubusercontent.com/72431640/214773095-367b5a03-12b6-46df-a3a4-1a6ae8a9b2f7.mp4
<Before ~ Progressing ~ Done>
https://user-images.githubusercontent.com/72431640/214773178-b923b135-4868-41ce-8cdf-653daed16658.mp4
- 먼저 지난번에 BlurView 뜨는 오류를 개선해야 합니다..! 지난 제 PR에서 발견됐고 원인도 @MMMIIIN 이 찾아줬었는데 그건 다음 PR 에 올릴 예정입니다!
- 코드 리팩토링을 좀 했습니다! `setup`이 `set`, `setUp`, `setup` 이렇게 다르기도 하고, present 하는 함수인데 `show`로 되어 있는것도 있어서 `present` 로 통일시켰습니다!
- 항상 그렇듯 gradient, cornerRadius, shadow 등을 동시에 넣을 때 어려움이 좀 있었습니다 ㅎㅎ... 제대로 했는지 확인 부탁드립니다!!
- close #277
> [ADD] JoinReflectionButton 새로운 UI 반영

- Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
여러 팀에 참여할 수 있게 되면서 바뀐 API 들 중 아직 변경이 안 된 애들을 반영하는 PR 입니닷
어,, 딱히 스샷이나 동영상 첨부할게 없네용
- fetchCurrentReflectionDetail 의 baseUrl -> baseUrl2로 변경
- deleteUser의 baseUrl -> baseUrl2로 변경
reflection 생성, 삭제, 변경 등 테스트!
유저 탈퇴 테스트!
- close #332
> [CHORE] Id가 맡은 API 수정사항들 반영

- Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
- Maddori.Apple/Maddori.Apple/Network/Response/FeedBackResponse.swift
api 주소 변경과 동시에 수정된 response 작업입니다.
없습니다.
- fetchPastReflectionList v1->v2
- fetchCertainTypeFeedbackAllID v1->v2
- ReflectionResponse 안쓰는 것들 삭제
336 브랜치로 오셔서 나의 회고 실행해보시고 회고 목록이 잘 뜨는지, 회고를 들어 간 후 continue stop이 잘 뜨는지 확인해보시면 됩니다.
- close #336
> [CHORE] api 주소 변경과 동시에 수정된 response 작업입니다.

- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
- Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
| 기존 | 현재 |
| ----| ----|
|<img src = "https://user-images.githubusercontent.com/59243274/231708521-372b7028-92f8-4bc1-9553-5900a403529f.png" width = "350"> |<img src = "https://user-images.githubusercontent.com/59243274/231708786-5644d259-2198-4012-b061-eecb14b9064c.png" width = "350">|
이런식으로 변경 됨에 따라 UI 변경하는 PR 입니다. 
- 케미가 만든 MemberInformationView 를 재 사용해서 만들었습니다. 
브랜치로 오셔서 피드백 주는 화면오시면 됩니다.
- 원래 만들었던 브랜치에서는 너무 꼬여서 새로운 브랜치 만들어서 작업했어요.
- 안쓰는 함수나 이런거 다 지워야 하는데.. 시간이 좀 없네요..하하 뭐가 있을까요?
- close #314
> [FEAT] 피드백 줄 때 맴버 선택 뷰 UI 변경 

- Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
- Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
- Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
팀 관리 뷰에서 로그아웃과 회원탈퇴를 하기 때문에 이 뷰에서 삭제했습니다.
- 버튼 및 함수 삭제
- TextLiteral 변수명 변경
feature/361-delete-button 오셔서 나의회고 보시면 됩니다.
- close #361
> [CHORE] 회원탈퇴/로그아웃 버튼 삭제하기
